theme: minima
title: pushpraj jaiswal blogging site
author: pushpraj jaiswal
email: pushprajapp12@gmail.com
description: > hello friends this site for you you learn about programing and many more content so and how to learn github. # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: pushprajjaiswa # DO NOT include the @ character, or else the build will fail!
github_username:  binaryBeast-creater # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
